### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by rajdeepbharati** [lassalleloan/docker-cisco-packet-tracer#1]
I have followed the instructions in the readme, pulled the docker image, etc. Could you tell how to use it? Is the GUI running as a webapp on some port? Sorry for the trivial question, I'm a newbie in this field.

**Comment by lassalleloan** [comment]
The GUI is running through the XQuartz window server. Normally, after the execution of the command docker run, a pop-up with Cisco Packet Tracer opens.
This project worked very well two years ago. And it was useful because Cisco Packet Tracer was not available on macOS.

But now, I admit it, it is useless, does not work well and I have not kept it updated.
Plus, XQuartz window server has been no longer updated for a very long time (last release on 2016-10-29) and X Window System (X11) will no longer be used on MacOS Catalina.

Now, Cisco provide a version of their tool on Linux, Windows and macOS. I therefore advise you to use the one that suits you.

However, if you really want to use a Docker container to run Cisco Packet Tracer, I can redirect you to jlesage’s repositories like https://github.com/jlesage/docker-baseimage-gui and https://github.com/jlesage/docker-filezilla. I don't know if this will work with Cisco Packet Tracer, but this person has done an incredible job on running GUI applications in Docker containers. 
I plan to delete my repository because I think  it is no longer useful, does not work well and I have not kept it updated.

I hope I have answered to your questions.
Thank you for your interest in my repository.

**Comment by rajdeepbharati** [comment]
> Now, Cisco provide a version of their tool on Linux, Windows and macOS. I therefore advise you to use the one that suits you.

Yes, I found the macOS version in the cisco website, so I'll use that one. 
Thank you for the help.
